language: node_js
node_js:
 - "8.0"
services:
 - redis
before_install:
 - "npm install -g grunt-cli jasmine-node"
install:
 - "npm install"
script:
 - "npm test"
branches:
  only:
    - master
    - develop
