language: node_js
node_js:
 - "0.12"
services:
 - redis
before_install:
 - "npm install -g grunt-cli coffee-script jasmine-node"
install:
 - "npm install"
script:
 - "npm test"
branches:
  only:
    - master
    - develop
