language: node_js
node_js:
 - "7.0"
services:
 - redis
before_install:
 - "npm install -g grunt-cli coffee-script jasmine-node@1.14.5"
install:
 - "npm install"
script:
 - "npm test"
branches:
  only:
    - master
    - develop