version: 2
jobs:
  build:
    shell: /bin/bash
    docker:
      - image: quay.io/redsift/nodeos
    steps:
      - checkout
      - run: npm i
      - run: npm i -g grunt-cli
      - run: grunt
      - run: npm run test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master