version: 2
jobs:
  build:
    shell: /bin/bash
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run: pwd
      - run: npm i && npm i grunt-cli && ./node_modules/.bin/grunt && npm run test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: patched