version: 2
jobs:
  build:
    shell: /bin/bash
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      # default user is circleci not root
      - run: sudo npm i -g grunt-cli
      - run: grunt
      - run: npm test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: patched